package enums;

public enum AccidentReportStatus {
    RECEIVED,
    INVESTIGATING,
    PAYMENT_REVIEW,
    COMPLETED,
    DOCUMENT_PENDING,
    FIELD_INVESTIGATION_REQUIRED,
    APPROVAL_REQUIRED,
    REJECTED,
    FRAUD_INVESTIGATION,
    REINVESTIGATION_REQUIRED,
    TRANSFERRED_TO_LEGAL,
    OUTSOURCED_INVESTIGATION,
    TEMP_SAVED
}
