spring.application.name=boonsan-api
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/boonsan}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

mybatis.mapper-locations=classpath*:mappers/**/*.xml
mybatis.type-aliases-package=com.boonsan.model
mybatis.configuration.map-underscore-to-camel-case=true